name: workflow

on:
  push:
    branches:
      - backend-v2
  pull_request:
    branches:
      - backend-v2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 17

    - name: Build with Maven
      run: | 
        cd PluggableAuth
        mvn clean package

    - name: Build Docker image
      run: docker build -t backend:latest .
