name: workflow

on:
  push:
    branches: [ backend-v2 ]
  pull_request:
    branches: [ backend-v2 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag arangra/email-client:$(date +%s)
